# Project basics
title: ErikTailor
tagline: My personal blog website
description: This is my personal blog website
author: ErikTailor
logo: /assets/img/eriktailor_logo_dark.webp
locale: hu
baseurl: ""
url: ""

# Exclude files from compiling
exclude:
  - CHANGELOG.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
  - .DS_Store
  - .jekyll-cache
  - assets/css/bootstrap/

# Livereload
livereload: true

# Sass
sass:
  sourcemap: never
  style: compressed

# Autoprefixer
autoprefixer:
  browsers:
    - last 2 versions

# Minifier
jekyll-minifier:
  exclude: ["sitemap.xml"]
  preserve_php: true
  remove_intertag_spaces: true

# Webp generation
webp:
  enabled: true
  quality: 80
  img_dir: ["/assets/img/"]
  nested: true
  formats: [".jpeg", ".jpg", ".png", ".tiff"]
  regenerate: false

# Tags
tag_page_layout: tag_page
tag_page_dir: tag

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer
  - jekyll-minifier
  - jekyll-webp
  - jekyll-seo-tag
  - jekyll/tagging
